StockInsight/StockInsight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('django.contrib.auth.urls')),
    path('', include('portfolio.urls')),
]

StockInsight/portfolio/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.dashboard_view, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('account/edit/', views.account_edit_view, name='account_edit'),
    path('account/history/', views.account_history_view, name='account_history'),
    path('portfolio/', views.portfolio_view, name='portfolio'),
    path('market/<str:selected_stock>/<str:window>/', views.market_view, name='market_view'),
    path('market/', views.market_view, name='market'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/<str:window>/', views.dashboard_view, name='dashboard_with_window'),
    path('currencies/currency/<str:search>/<str:window>/', views.currency_view, name='currency_view'),

    # jak nie działa to odkomencić
    # path('account/', views.account_view, name='account'),

    # FORUM MODULE
    path('forum/', views.post_list, name='post_list'),
    path('forum/post/<int:pk>/', views.post_detail, name='post_detail'),
    path('forum/post/new/', views.post_new, name='post_new'),
    # -------------
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StockInsight/portfolio/models.py
from django.db import models
import requests
import json
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django import forms


class AccountForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['username', 'profile_picture']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)

    def __str__(self):
        return self.user.username


class StockData(models.Model):
    timestamp = models.DateTimeField()
    price = models.FloatField()

    objects = models.Manager()

    @staticmethod
    def fetch_and_process_data(search, window):
        SERP_API_KEY = '675093b1d4f189f365f7642d8c97aebbc69de8b3d21bac35f6dbab3d8d1be778'
        response = requests.get(f'https://serpapi.com/search.json?engine=google_finance&q={search}&window={window}&api_key={SERP_API_KEY}')
        data = response.json()
        print(data)

        stock_data = data.get('graph', [])
        filtered_stock_data = []
        last_timestamp = None

        # Determine the time delta based on the window
        time_delta = {
            '1d': timedelta(minutes=10),
            '5d': timedelta(hours=2),
            '1m': timedelta(days=1),
            '6m': timedelta(weeks=1),
            '1y': timedelta(weeks=2),
            '5y': timedelta(weeks=4)
        }.get(window, timedelta(minutes=10))  # Default to 10 minutes if window is unknown

        for item in stock_data:
            date_str = item['date'].replace('-05:00', '')
            timestamp = datetime.strptime(date_str, '%b %d %Y, %I:%M %p %Z')
            rounded_timestamp = timestamp.replace(minute=0, second=0, microsecond=0)
            if timestamp.minute >= 30:
                rounded_timestamp += timedelta(hours=1)
            if last_timestamp is None or rounded_timestamp >= last_timestamp + time_delta:
                filtered_stock_data.append({'timestamp': rounded_timestamp.isoformat(), 'price': item['price']})
                last_timestamp = rounded_timestamp
        print(json.dumps(filtered_stock_data))
        return json.dumps(filtered_stock_data)

    @staticmethod
    def get_available_windows():
        return ['1d', '5d', '1m', '6m', '1y', '5y']

    @staticmethod
    def get_currencies():
        return ["USD", "EUR", "GBP", "JPY", "AUD", "CAD", "CHF", "CNY", "NZD", "BTC", "ETH", "XRP", "BCH", "ADA", "DOT", "BNB", "USDT"]

    @staticmethod
    def get_available_stocks():
        return ['AAPL', 'GOOGL', 'AMZN', 'MSFT', 'TSLA', 'FB', 'NVDA', 'PYPL', 'ADBE', 'INTC']

class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    objects = models.Manager()


class Currency(models.Model):
    name = models.CharField(max_length=50)
    value = models.FloatField()

    objects = models.Manager()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts', null=True, blank=True)
    title = models.CharField(max_length=255)
    related_tickers = models.CharField(max_length=25)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment on {self.post.title}'

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} bought {self.quantity} shares of {self.company}"

StockInsight/portfolio/views.py
from django.contrib.auth import login, authenticate, logout
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages

from .models import StockData, Transaction, Post
from .forms import LoginForm, RegisterForm, AccountForm, PostForm, CommentForm

from django.http import JsonResponse
from urllib.parse import urljoin, urlparse
import json
import requests
from bs4 import BeautifulSoup
import ast
from datetime import datetime, timedelta

DISABLE_ARTICLES = False


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
    else:
        form = LoginForm()
    return render(request, 'portfolio/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return render(request, 'portfolio/logout.html')


def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            profile_picture = form.cleaned_data.get('profile_picture')
            if profile_picture:
                user.profile.profile_picture = profile_picture
                user.profile.save()
            login(request, user)
            return redirect('dashboard')
    else:
        form = RegisterForm()
    return render(request, 'portfolio/register.html', {'form': form})


@login_required
def account_edit_view(request):
    if request.method == 'POST':
        form = AccountForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully.')
            return redirect('account_edit')
    else:
        form = AccountForm(instance=request.user)
    return render(request, 'portfolio/account_edit.html', {'form': form})

@login_required
def account_history_view(request):
    transactions = Transaction.objects.filter(user=request.user)
    return render(request, 'portfolio/account_history.html', {'transactions': transactions})


def portfolio_view(request):
    return render(request, 'portfolio/portfolio.html')



@login_required
def market_view(request, selected_stock="NVDA", window="1d"):
    search = selected_stock
    if "%3ANASDAQ" not in search or ":NASDAQ" not in search:
        search += "%3ANASDAQ"
    available_stocks = StockData.get_available_stocks()
    available_windows = StockData.get_available_windows()
    stock_data = StockData.fetch_and_process_data(search, window)

    if request.method == 'POST':
        try:
            quantity = int(request.POST['quantity'])
            Transaction.objects.create(user=request.user, company=selected_stock, quantity=quantity)
            messages.success(request, f'You have successfully bought {quantity} shares of {selected_stock}. <a href="{reverse("account_history")}">View History</a>')
        except (ValueError, KeyError):
            messages.error(request, 'Invalid quantity. Please enter a valid number.')

    # POSTS
    posts = Post.objects.filter(related_tickers__contains=selected_stock).order_by('-created_at')
    for post in posts:
        post.related_tickers = ast.literal_eval(post.related_tickers)

    # ----

    context = {
        'search': search,
        'available_stocks': available_stocks,
        'available_windows': available_windows,
        'selected_stock': selected_stock,
        'selected_window': window,
        'stock_data': stock_data,
        # ARTICLES
        'articles': fetch_articles(selected_stock),
        # POSTS
        'posts': posts,
    }
    return render(request, 'market.html', context)

@login_required
def dashboard_view(request, window="1d"):
    search = "EUR-USD"
    stock_data = StockData.fetch_and_process_data(search, window)
    stock_data_json = json.dumps(stock_data) if stock_data else '[]'
    available_windows = StockData.get_available_windows()
    available_currencies = StockData.get_currencies()
    currencies = search.split('-')

    # POSTS
    posts = Post.objects.all().order_by('-created_at')
    for post in posts:
        post.related_tickers = ast.literal_eval(post.related_tickers)

    # ----

    context = {
        'search': search,
        'window': window,
        'stock_data': stock_data,
        'stock_data_json': stock_data_json,
        'available_currencies': available_currencies,
        'available_windows': available_windows,
        'from_currency': currencies[0],
        'to_currency': currencies[1],
        # ARTICLES
        'articles': fetch_articles(),
        # POSTS
        'posts': posts,
    }
    return render(request, 'dashboard.html', context)


@login_required
def currency_view(request, search, window="1d"):
    stock_data = StockData.fetch_and_process_data(search, window)
    stock_data_json = json.dumps(stock_data) if stock_data else '[]'
    available_windows = StockData.get_available_windows()
    available_currencies = StockData.get_currencies()
    currencies = search.split('-')

    # POSTS
    posts = Post.objects.filter(Q(related_tickers__contains=currencies[0]) |
                                Q(related_tickers__contains=currencies[1])).order_by('-created_at')
    for post in posts:
        post.related_tickers = ast.literal_eval(post.related_tickers)

    # ----

    context = {
        'search': search,
        'window': window,
        'stock_data': stock_data,
        'stock_data_json': stock_data_json,
        'available_currencies': available_currencies,
        'available_windows': available_windows,
        'from_currency': currencies[0],
        'to_currency': currencies[1],
        # ARTICLES
        # 'articles': fetch_articles(search),
        # POSTS
        'posts': posts,
    }
    return render(request, 'currencies/currency.html', context)


@login_required
def chart_view(request, search, window):
    stock_data = StockData.fetch_and_process_data(search, window)
    stock_data_json = json.dumps(stock_data) if stock_data else '[]'

    # Detect currency symbol
    currency_symbol = {
        "USD": "$",
        "EUR": "€",
        "GBP": "£",
        "JPY": "¥",
        "AUD": "A$",
        "CAD": "C$",
        "CHF": "CHF",
        "CNY": "¥",
        "NZD": "NZ$",
        "BTC": "₿",
        "ETH": "Ξ",
        "XRP": "XRP",
        "BCH": "BCH",
        "ADA": "₳",
        "DOT": "DOT",
        "BNB": "BNB",
        "USDT": "₮"
    }.get(search.split('-')[1], "")

    # Currency full names
    currency_names = {
        "USD": "US Dollar",
        "EUR": "Euro",
        "GBP": "British Pound",
        "JPY": "Japanese Yen",
        "AUD": "Australian Dollar",
        "CAD": "Canadian Dollar",
        "CHF": "Swiss Franc",
        "CNY": "Chinese Yuan",
        "NZD": "New Zealand Dollar",
        "BTC": "Bitcoin",
        "ETH": "Ethereum",
        "LTC": "Litecoin",
        "XRP": "Ripple",
        "BCH": "Bitcoin Cash",
        "ADA": "Cardano",
        "DOT": "Polkadot",
        "BNB": "Binance Coin",
        "USDT": "Tether"
    }

    # Generate chart label
    currencies = search.split('-')
    if len(currencies) == 2:
        from_currency = currency_names.get(currencies[0], currencies[0])
        to_currency = currency_names.get(currencies[1], currencies[1])
        chart_label = f'{from_currency} to {to_currency}'
    else:
        chart_label = f'Trending {search}'

    return render(request, 'chart.html', {
        'stock_data': stock_data_json,
        'chart_label': chart_label,
        'currency_symbol': currency_symbol
    })


# FORUM MODULE

@login_required
def post_list(request):
    posts = Post.objects.all().order_by('-created_at')

    ticker_filter = request.GET.get('ticker')
    title_filter = request.GET.get('title')

    if ticker_filter:
        posts = posts.filter(related_tickers__contains=ticker_filter)

    if title_filter:
        posts = posts.filter(title__contains=title_filter)

    for post in posts:
        post.related_tickers = ast.literal_eval(post.related_tickers)

    tickers = StockData.get_currencies() + StockData.get_available_stocks()
    return render(request, 'forum/post_list.html', {
        'posts': posts,
        'tickers': tickers
    })


@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.related_tickers = ast.literal_eval(post.related_tickers)
    comments = post.comments.all().order_by('-created_at')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'forum/post_detail.html', {
                                                      'post': post,
                                                      'form': form,
                                                      'comments': comments})


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('post_list')
    else:
        form = PostForm()
    return render(request, 'forum/post_form.html', {'form': form})

# --------------------------------------------
# --------------- FUNCTIONS ------------------

StockInsight/templates/portfolio/account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
    <title>Account</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container mt-4" style="background-color: white">
        <h1>Account</h1>
        {% if messages %}
        <div class="alert alert-success">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save changes</button>
            <a href="{% url 'dashboard' %}" class="btn btn-secondary">Back to Dashboard</a>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

StockInsight/templates/portfolio/account_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style_edit.css' %}">
    <title>Edit Profile</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container mt-4" style="background-color: white">
        <h1 class="text-center">Edit Profile</h1>
        {% if messages %}
            <div class="alert alert-success" role="alert">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save changes</button>
            <a href="{% url 'dashboard' %}" class="btn btn-secondary">Back to Dashboard</a>
        </form>
    </div>
    {% include "footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

StockInsight/templates/portfolio/account_history.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style_market.css' %}">
    <title>History</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container mt-4" style="background-color: white">
    <h2>History</h2>
    <table class="table">
        <thead>
        <tr>
            <th>Company</th>
            <th>Quantity</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.company }}</td>
                <td>{{ transaction.quantity }}</td>
                <td>{{ transaction.date }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% include "footer.html" %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

StockInsight/templates/portfolio/login.html
<!-- login.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
    <title>Login</title>
</head>
<body>
<section class="container login_panel">
    <div class="row">
        <div class="col-6 short_about">
            <div class="text-center">
                <img src="{% static 'images/StockInsightLogoWhiteBlue.png' %}" alt="Logo"
                     class="img-fluid p-4 logo_login">
            </div>
            <div class="row mt-4">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-9">
                    <h2>Over 300,000 satisfied users</h2>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-9">
                    <h2>Over 2,000,000 transactions</h2>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-9">
                    <h2>More than $14,000,000 stolen</h2>
                </div>
            </div>
            <div class="row mt-4 mb-5">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-8">
                    <h2>At least $5,000,000 hidden by money mules</h2>
                </div>
            </div>
        </div>
        <div class="col-6 text-center short_login">
            <h1>Sign in</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-floating mt-4">
                        {{ field }}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% if field.errors %}
                            <div class="text-danger">
                                {{ field.errors|join:", " }}
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
                {% if form.non_field_errors %}
                    <div class="alert alert-danger mt-2">
                        {{ form.non_field_errors|join:", " }}
                    </div>
                {% endif %}
                <p class="mt-3">You don't have an account? <a href="{% url 'register' %}">Sign up</a></p>
                <button type="submit" class="btn btn-success btn-lg mt-2"
                        style="background-color: #2DB363">Submit
                </button>
            </form>
        </div>
    </div>
</section>
</body>
</html>

StockInsight/templates/portfolio/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style_dashboard.css' %}">
    <title>Logout</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container mt-4" style="background-color: white">
        <h1>Logout</h1>
        <div class="alert alert-info">
            You have successfully logged out.
        </div>
        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

StockInsight/templates/portfolio/portfolio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Twoje portfolio</title>
</head>
<body>
    <h1>Witaj w swoim portfolio!</h1>
    <p>Tu znajdziesz szczegóły swojego portfolio inwestycyjnego.</p>
</body>
</html>

StockInsight/templates/portfolio/register.html
<!-- register.html -->
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/style.css' %}">
    <script src="{% static 'portfolio/script.js' %}"></script>
    <title>Register</title>
</head>
<body>
<section class="container login_panel">
    <div class="row">
        <div class="col-6 short_about">
            <div class="text-center">
                <img src="{% static 'images/StockInsightLogoWhiteBlue.png' %}" alt="Logo"
                     class="img-fluid p-4 logo_login">
            </div>
            <div class="row mt-4">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-9">
                    <h2>Over 300,000 satisfied users</h2>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-9">
                    <h2>Over 2,000,000 transactions</h2>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-9">
                    <h2>More than $14,000,000 stolen</h2>
                </div>
            </div>
            <div class="row mt-4 mb-5">
                <div class="col-3 text-end">
                    <img src="{% static 'images/check_icon.png' %}" alt="check" class="check_icon">
                </div>
                <div class="col-8">
                    <h2>At least $5,000,000 hidden by money mules</h2>
                </div>
            </div>
        </div>
        <div class="col-6 text-center short_login">
            <h1>Register</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="my-3">
                    {{ form.username }}
                    {% if form.username.errors %}
                        <ul class="errorlist">
                            {% for error in form.username.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>

                <div class="my-3">
                    {{ form.password1 }}
                    {% if form.password1.errors %}
                        <ul class="errorlist">
                            {% for error in form.password1.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="my-3">
                    {{ form.password2 }}
                    {% if form.password2.errors %}
                        <ul class="errorlist">
                            {% for error in form.password2.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
                <div class="mb-3 clear_form">
                    <label for="id_profile_picture" class="form-label">Profile Picture:</label>
                    <div class="input-group">
                        {{ form.profile_picture|add_class:"form-control" }}
                    </div>
                    {% if form.profile_picture.errors %}
                        <div class="alert alert-danger" role="alert">
                            <ul class="list-unstyled">
                                {% for error in form.profile_picture.errors %}
                                    <li><i class="bi bi-exclamation-circle"></i> {{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                <button type="button" class="btn btn-outline-secondary mt-2" id="clear_file" style="display: none">Clear</button>
                </div>
                <a href="{% url 'login' %}" class="btn btn-secondary btn-lg mb-2" role="button"
                   style="color: #FFFFFF; font-weight: normal">Back</a>
                <button type="submit" class="btn btn-success btn-lg mb-2"
                        style="background-color: #2DB363; font-weight: normal">Register
                </button>
            </form>
        </div>
    </div>
</section>
</body>
</html>